const executeQuery = require('../database/executeQuery')

class BonusRepository {

	async findBonus() {

		let bonus = await executeQuery(`
			SELECT
				PCBONUSC.NUMBONUS,
				PCBONUSC.DATABONUS,
				PCBONUSC.VALORTOTAL,
				PCBONUSC.DTMONTAGEM,
				PCNFENTPREENT.NUMNOTA,
				PCFORNEC.FORNECEDOR
			FROM PCBONUSC
			JOIN PCNFENTPREENT ON PCNFENTPREENT.NUMBONUS = PCBONUSC.NUMBONUS
			JOIN PCFORNEC ON PCNFENTPREENT.CODFORNEC = PCFORNEC.CODFORNEC
			WHERE PCBONUSC.DTFECHAMENTO IS NULL AND PCBONUSC.DTCANCEL IS NULL
			ORDER BY PCBONUSC.DTMONTAGEM ASC
		`)

		return bonus
	}

	async findBonusItens({ numbonus }) {

		let itens = await executeQuery(`
			SELECT
			PCBONUSI.CODPROD,
			PCBONUSI.QTNF,
			PCBONUSI.QTENTRADA,
			PCBONUSI.DTVALIDADE,
			PCPRODUT.DESCRICAO,
			PCPRODUT.EMBALAGEM,
			NVL(REGEXP_SUBSTR(PCPRODUT.DIRFOTOPROD, '[^\\]+$'), 'not-found.png') AS DIRFOTOPROD,
			PCMARCA.MARCA
			FROM PCBONUSI
			JOIN PCPRODUT ON PCPRODUT.CODPROD = PCBONUSI.CODPROD
			LEFT JOIN PCMARCA ON PCPRODUT.CODMARCA = PCMARCA.CODMARCA
			WHERE PCBONUSI.NUMBONUS = :numbonus
			ORDER BY PCPRODUT.DESCRICAO
		` ,{ numbonus })

		return itens
	}

}

module.exports = new BonusRepository()
